# Generated by Django 2.2.10 on 2021-11-16 20:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('start_date', models.DateTimeField(verbose_name='Дата старта')),
                ('finish_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('description', models.CharField(blank=True, default='', max_length=256, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Опросник',
                'verbose_name_plural': 'Опросники',
                'ordering': ('-finish_date',),
            },
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Анкетируемый пользователь',
                'verbose_name_plural': 'Анкетируемые пользователи',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_text', models.CharField(max_length=256, verbose_name='Вопрос')),
                ('q_type', models.SmallIntegerField(choices=[(0, 'ответ текстом'), (1, 'ответ с выбором одного варианта'), (2, 'ответ с выбором нескольких вариантов')], default=0, verbose_name='Тип вопроса')),
                ('required', models.BooleanField(default=False, verbose_name='Обязательный')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionnaire.Questionnaire', verbose_name='Опросник')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_text', models.CharField(max_length=256, verbose_name='Ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionnaire.Question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='QuestionnairePassing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_filled', models.TextField(verbose_name='Ответы на вопросы')),
                ('pass_date', models.DateTimeField(auto_now=True, verbose_name='Дата прохождения опросника')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questionnaire.Questionnaire', verbose_name='Опросник')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_passing', to='questionnaire.Respondent', verbose_name='Респондент')),
            ],
            options={
                'verbose_name': 'Ответы респондентов',
                'verbose_name_plural': 'Ответы респондентов',
                'unique_together': {('respondent', 'quest')},
            },
        ),
    ]
