# Generated by Django 2.2.10 on 2021-11-16 10:57

import datetime
from django.db import migrations
from django.utils import timezone


def insert_data(apps, schema_editor):

    now = timezone.now()
    Questionnaire = apps.get_model('questionnaire', 'Questionnaire')
    Question = apps.get_model('questionnaire', 'Question')
    Answer = apps.get_model('questionnaire', 'Answer')

    q_obj = Questionnaire.objects.create(
        name='Анкета фитнес клуба', start_date=now, finish_date=now + datetime.timedelta(days=5),
        description='Опрос посетителей клуба'
    )

    qn_obj = Question.objects.create(
        quest=q_obj, q_text='Как Вы узнали о нашем фитнес-центре?', q_type=1, required=True
    )
    Answer.objects.bulk_create([
        Answer(question=qn_obj, a_text='Самостоятельный поиск в Интернете'),
        Answer(question=qn_obj, a_text='E-mail рассылка'),
        Answer(question=qn_obj, a_text='Рекламный баннер'),
    ])

    Question.objects.create(
        quest=q_obj, q_text='Имя и фамилия Вашего личного тренера?', q_type=0, required=True
    )

    qn_obj = Question.objects.create(
        quest=q_obj, q_text='Какие направления посещали?', q_type=2, required=True
    )
    Answer.objects.bulk_create([
        Answer(question=qn_obj, a_text='Тренажёры'),
        Answer(question=qn_obj, a_text='Степ-аэробика'),
        Answer(question=qn_obj, a_text='Бассейн'),
    ])

    q_obj = Questionnaire.objects.create(
        name='Удовлетворенность авиапассажиров', start_date=now, finish_date=now + datetime.timedelta(days=8),
        description='Опрос для Аэрофлота'
    )

    qn_obj = Question.objects.create(
        quest=q_obj, q_text='Ваш пол?', q_type=1, required=True
    )
    Answer.objects.bulk_create([
            Answer(question=qn_obj, a_text='Мужской'),
         Answer(question=qn_obj, a_text='Женский')
    ])

    Question.objects.create(
        quest=q_obj, q_text='', q_type=0, required=True
    )

    qn_obj = Question.objects.create(
        quest=q_obj, q_text='Что, по Вашему мнению, мы бы могли улучшить?', q_type=2, required=True
    )
    Answer.objects.bulk_create([
        Answer(question=qn_obj, a_text='Время отправления / прибытия было удобнее'),
        Answer(question=qn_obj, a_text='Лучшие условия рейса (отсутствие пересадок / меньше время ожидания при пересадке)'),
        Answer(question=qn_obj, a_text='Личное предпочтение'),
    ])

    q_obj = Questionnaire.objects.create(
        name='Опрос клиентов о качестве обслуживания', start_date=now, finish_date=now + datetime.timedelta(days=8),
        description='Оцените, пожалуйста, следующие параметры по шкале от 1 до 5, где 1 - минимальная оценка, 5 - максимальная'
    )

    qn_obj = Question.objects.create(
        quest=q_obj, q_text='Как долго Вы ожидали своей очереди для разговора с клиентским сервисом?', q_type=1, required=True
    )
    Answer.objects.bulk_create([
        Answer(question=qn_obj, a_text='1'),
        Answer(question=qn_obj, a_text='2'),
        Answer(question=qn_obj, a_text='3'),
        Answer(question=qn_obj, a_text='4'),
        Answer(question=qn_obj, a_text='5'),
    ])

    qn_obj = Question.objects.create(
        quest=q_obj, q_text='Насколько компетентными Вы считаете работников клиентского сервиса?', q_type=1, required=True
    )
    Answer.objects.bulk_create([
        Answer(question=qn_obj, a_text='1'),
        Answer(question=qn_obj, a_text='2'),
        Answer(question=qn_obj, a_text='3'),
        Answer(question=qn_obj, a_text='4'),
        Answer(question=qn_obj, a_text='5'),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_data),
    ]
